(define tolerance .000001)
(define (iterative-improve good-enough? improve)
  (define (iter x)
    (if (good-enough? x)
        x
        (iter (improve x))))
  (lambda (x)
    (iter x)))
(define (sqrt guess x)
  ((iterative-improve (lambda (guess)
                        (< (abs (- (square guess) x)) tolerance))
                      (lambda (guess)
                        (average guess (/ x guess))))
   guess))
(define (fixed-point f guess)
  ((iterative-improve (lambda (guess)
                        (< (abs (- guess (f guess))) tolerance))
                      (lambda (guess)
                        (f guess)))
   guess))
(define (square x)
  (* x x))
(define (average a b)
  (/ (+ a b) 2))
