(define (simpsons-rule f a b n)
  (define (simpson f a b n h)
    (define (y k)
      (f (+ a (* k h))))
    (define (term k)
      (cond ((or (= k 0) (= k n)) (y k))
            ((even? k) (* 2 (y k)))
            (else (* 4 (y k)))))
    (define (inc x)
      (+ x 1))
    (* (/ h 3) (sum term 0 inc n)))
  (simpson f a b n (/ (- b a) n)))
(define (sum f a next b)
  (cond ((> a b) 0)
        (else (+ (f a)
                 (sum f (next a) next b)))))
(define (cube x)
  (* x x x))
