;; a. The procedure p is appied 5 times when (sine 12.15) is evaluated.
;;
;; b. The order of growth in space and number of steps used by the process generated by the sine procedure when (sine a) is evaluated is
;;    Theta(n) and Theta(n), respectively.
