(define (multiply b n)
  (define (even? x)
    (= (remainder x 2) 0))
  (define (double x)
    (* x 2))
  (define (halve x)
    (/ x 2))
  (define (multiply-iter a b n)
    (cond ((= n 0) a)
          ((even? n) (multiply-iter a (double b) (halve n)))
          (else (multiply-iter (+ a b) b (- n 1)))))
  (multiply-iter 0 b n))
