(define (raise-real x)
  ((get-coercion 'real 'complex) x))
(define (raise-rational x)
  ((get-coercion 'rational 'real) x))
(define (raise-integer x)
  ((get-coercion 'integer 'rational) x))
(put 'raise 'real raise-real)
(put 'raise 'rational raise-rational)
(put 'raise 'integer raise-integer)
(define (raise x)
  (apply-generic 'raise x))
