(define (install-raise-package)
  (define (raise-real x)
    (make-from-real-imag x 0))
  (define (raise-rational x)
    (make-real (/ (car x) (cdr x))))
  (define (raise-integer x)
    (make-rational x 1))
  (put 'raise '(real) raise-real)
  (put 'raise '(rational) raise-rational)
  (put 'raise '(integer) raise-integer)
  'done)
(define (raise x)
  (apply-generic 'raise x))
