(define (install-=zero?-package)
  (define (=zero?-ordinary x) (= x 0))
  (define (=zero?-rational x) (= (numer x) 0))
  (define (=zero?-complex x) (and (= (real-part x) 0)
                                  (= (imag-part x) 0)))
  (put '=zero? '(scheme-number) =zero?-ordinary)
  (put '=zero? '(rational) =zero?-rational)
  (put '=zero? '(complex) =zero?-complex))
(define (=zero? x)
  (apply-generic '=zero? x))
