(define (make-segment start end)
  (cons start end))
(define (start-segment segment)
  (car segment))
(define (end-segment segment)
  (cdr segment))
(define (make-point x y)
  (cons x y))
(define (x-point point)
  (car point))
(define (y-point point)
  (cdr point))
(define (midpoint-segment segment)
  (midpoint (start-segment segment)
            (end-segment segment)))
(define (midpoint point1 point2)
  (make-point (average (x-point point1)
                       (x-point point2))
              (average (y-point point1)
                       (y-point point2))))
(define (average x y)
  (/ (+ x y) 2))
(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))
