(define dx .000001)
(define tolerance .000001)
(define (newtons-method g x)
  (fixed-point (average-damping (newtons-transform g)) x))
(define (newtons-transform g)
  (lambda (x)
    (- x (/ (g x)
            ((deriv g) x)))))
(define (deriv g)
  (lambda (x)
    (/ (- (g (+ x dx))
          (g x))
       dx)))
(define (fixed-point f x)
  (let ((next (f x)))
    (if (good-enough? x next)
        next
        (fixed-point f next))))
(define (good-enough? a b)
  (< (abs (- a b)) tolerance))
(define (average-damping f)
  (lambda (x)
    (average x (f x))))
(define (average a b)
  (/ (+ a b) 2))
