(define (prime? n)
  (define (square x)
    (* x x))
  (define (divides? a b)
    (= (remainder b a) 0))
  (define (prime-iter n k)
    (cond ((> (square k) n) n)
          ((divides? k n) k)
          (else (prime-iter n (+ k 1)))))
  (= (prime-iter n 2) n))
