(define (sqrt x)
  (define (abs x)
    (if (< x 0)
        (- x)
        x))
  (define (square x)
    (* x x))
  (define (good-enough? y x)
    (< (abs (- x (square y))) 0.000001))
  (define (improve y x)
    (/ (+ y (/ x y)) 2))
  (define (sqrt-iter y x)
    (if (good-enough? y x)
        y
        (sqrt-iter (improve y x) x)))
  (sqrt-iter 1.0 x))
