(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (change-password new-password)
    (set! password new-password))
  (lambda (current-password operation)
    (if (eq? current-password password)
        (cond ((eq? operation 'withdraw) withdraw)
              ((eq? operation 'deposit) deposit)
              ((eq? operation 'change-password) change-password)
              (else (error "Unknown request -- MAKE-ACCOUNT" operation)))
        (lambda (x) "Incorrect password"))))
(define (make-joint cur-acc cur-password new-password)
  (let ((new-acc cur-acc))
    (let ((result ((new-acc cur-password 'change-password) new-password)))
      (if (and (string? result) (string=? result "Incorrect password"))
          (display "\"Incorrect password\"")
          new-acc))))
