(define (make-account balance password)
  (define counter 0)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch try-password m)
    (if (eq? try-password password)
        (begin (cond ((eq? m 'withdraw) withdraw)
                     ((eq? m 'deposit) deposit)
                     (else (error "Unknown request -- MAKE-ACCOUNT" m)))
               (set! counter 0))
        (begin (lambda (x) "Incorrect password")
               (set! counter (+ counter 1))
               (if (> counter 7)
                   call-the-cops))))
  dispatch)
