(define (cons x y)
  (lambda (m)
    (cond ((eq? m 'car) x)
	  ((eq? m 'cdr) y)
	  ((eq? m 'set-car!) (lambda (v) (set! x v)))
	  ((eq? m 'set-cdr!) (lambda (v) (set! y v)))
	  (else (error "Undefined operation -- CONS" m)))))
(define (car pair) (pair 'car))
(define (cdr pair) (pair 'cdr))
(define (set-car! pair v)
  ((pair 'set-car!) v)
  pair)
(define (set-cdr! pair v)
  ((pair 'set-cdr!) v)
  pair)
